model_configuration:
  input_shape:
  - 1
  - 3
  - 640
  - 640
  input_type: NV12
  output_type: FP32
compiler_options:
  working_mode: bayes
  optimize_level: O3
quantization:
  calibration_data: /home/sunrise/yahboomcar_ws/src/laser_calibration/models/calibration_images
  calibration_size: 100
  precision: int8
input_parameters:
- name: images
  type: image
  format: NV12
